import { useState } from 'react';

// This page reads a token from the URL, for example /reset-password?token=abc123
// The token comes from the link generated by forgot_password.php

function ResetPassword() {
  const params = new URLSearchParams(window.location.search);
  const token = params.get('token') || '';

  const [newPassword, setNewPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setMessage('');

    try {
      const response = await fetch('/backend/api/auth/reset_password.php', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token, new_password: newPassword })
      });

      const data = await response.json();

      if (!response.ok) {
        setMessage(data.error || 'Could not reset password');
        setLoading(false);
        return;
      }

      setMessage('Password reset. You can now log in.');
      setDone(true);
    } catch (err) {
      setMessage('Could not reach the server');
    }

    setLoading(false);
  };

  if (!token) {
    return <p>This reset link is missing a token. Request a new one from the forgot password page.</p>;
  }

  return (
    <div className="reset-password-page">
      <h2>Reset Password</h2>

      {!done && (
        <form onSubmit={handleSubmit}>
          <div className="password-field">
            <input
              type={showPassword ? 'text' : 'password'}
              placeholder="New password"
              value={newPassword}
              onChange={(e) => setNewPassword(e.target.value)}
              minLength={8}
              required
            />
            <button type="button" onClick={() => setShowPassword(!showPassword)}>
              {showPassword ? 'Hide' : 'Show'}
            </button>
          </div>
          <button type="submit" disabled={loading}>
            {loading ? 'Saving' : 'Reset Password'}
          </button>
        </form>
      )}

      {message && <p className="reset-password-message">{message}</p>}
    </div>
  );
}

export default ResetPassword;
